# This is a basic workflow to help you get started with Actions

name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Pandoc
              run: sudo apt-get install pandoc

            - name: Install Node Deps
              run: npm ci

            - name: Create Markdown
              run: npm start

            - name: Check Dir
              run: ls

            - name: Run Pandoc
              run: pandoc -o ${GITHUB_WORKSPACE}/dist/smiling-proud-wanderer.epub ${GITHUB_WORKSPACE}/metadata.yaml ${GITHUB_WORKSPACE}/dist/markdown/index.md ${GITHUB_WORKSPACE}/dist/markdown/chapter-{1..40}.md --css epub.css --epub-chapter-level=2

            - name: Download EPUB
              uses: actions/download-artifact@v2
              with:
                  name: "smiling-proud-wanderer.epub"
                  path: "dist"
